"""empty message

Revision ID: 652708d988a4
Revises: a0913acd5219
Create Date: 2019-05-03 00:42:30.687373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652708d988a4'
down_revision = 'a0913acd5219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=16), nullable=True),
    sa.Column('fleet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
